version: "3"

services:
  model:
    container_name: covid19-regression-model
    command: python app.py
    # entrypoint: 
    #   - python 
    #   - app.py
    build: model-api/
    image: model-api:v02
    env_file: .env
    ports:
      - $PORT_MODEL:5000
    volumes: 
      - $MODELS_PATH:/app/models
      - $DATA_FOLDER_PROCESSED:/app/data/processed
    restart: always
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.15"
      #     memory: 1024M
      restart_policy:
        condition: on-failure

# volumes: 
#   - pipelinedata:


